import type { User, Scan, Finding, FindingSummary, Report, Settings, AgentLog } from "@/types";

// ── Helper ──────────────────────────────────────────────────────────────
const uid = (i: number) => `00000000-0000-4000-a000-${String(i).padStart(12, "0")}`;
const ago = (days: number) => new Date(Date.now() - days * 86400000).toISOString();
const agoMin = (mins: number) => new Date(Date.now() - mins * 60000).toISOString();

// ── Users ───────────────────────────────────────────────────────────────
export const mockUser: User = {
  id: uid(1),
  email: "demo@bugbounty.com",
  username: "demo",
  created_at: ago(30),
};

// ── Scans ───────────────────────────────────────────────────────────────
export const mockScans: Scan[] = [
  {
    id: uid(100),
    user_id: uid(1),
    target_url: "https://juice-shop.herokuapp.com",
    status: "completed",
    scan_type: "full",
    progress: 100,
    current_agent: null,
    started_at: ago(2),
    completed_at: ago(2),
    duration_seconds: 347,
    created_at: ago(2),
    target_scope_include: ["*.herokuapp.com"],
    target_scope_exclude: null,
  },
  {
    id: uid(101),
    user_id: uid(1),
    target_url: "https://demo.testfire.net",
    status: "completed",
    scan_type: "quick",
    progress: 100,
    current_agent: null,
    started_at: ago(5),
    completed_at: ago(5),
    duration_seconds: 124,
    created_at: ago(5),
    target_scope_include: null,
    target_scope_exclude: null,
  },
  {
    id: uid(102),
    user_id: uid(1),
    target_url: "https://hackerone.com",
    status: "running",
    scan_type: "full",
    progress: 42,
    current_agent: "scanner",
    started_at: agoMin(12),
    completed_at: null,
    duration_seconds: null,
    created_at: agoMin(12),
    target_scope_include: ["*.hackerone.com"],
    target_scope_exclude: ["docs.hackerone.com"],
  },
  {
    id: uid(103),
    user_id: uid(1),
    target_url: "https://example-bank.com",
    status: "completed",
    scan_type: "full",
    progress: 100,
    current_agent: null,
    started_at: ago(8),
    completed_at: ago(8),
    duration_seconds: 512,
    created_at: ago(8),
    target_scope_include: null,
    target_scope_exclude: null,
  },
  {
    id: uid(104),
    user_id: uid(1),
    target_url: "https://vulnerable-app.local",
    status: "failed",
    scan_type: "quick",
    progress: 15,
    current_agent: "recon",
    started_at: ago(10),
    completed_at: ago(10),
    duration_seconds: 22,
    created_at: ago(10),
    target_scope_include: null,
    target_scope_exclude: null,
  },
  {
    id: uid(105),
    user_id: uid(1),
    target_url: "https://staging.myapp.io",
    status: "completed",
    scan_type: "quick",
    progress: 100,
    current_agent: null,
    started_at: ago(1),
    completed_at: ago(1),
    duration_seconds: 98,
    created_at: ago(1),
    target_scope_include: null,
    target_scope_exclude: null,
  },
];

// ── Findings ────────────────────────────────────────────────────────────
export const mockFindings: Record<string, Finding[]> = {
  [uid(100)]: [
    {
      id: uid(200),
      scan_id: uid(100),
      type: "XSS",
      severity: "high",
      cvss_score: 7.5,
      cvss_vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:H/A:N",
      cwe: "CWE-79",
      title: "Reflected Cross-Site Scripting in Search Parameter",
      url: "https://juice-shop.herokuapp.com/rest/products/search?q=",
      parameter: "q",
      method: "GET",
      evidence: '<script>alert("XSS")</script> reflected in response body without encoding',
      confirmed: true,
      fix_recommendation: "Implement proper output encoding using a context-aware encoder. Apply Content-Security-Policy headers to mitigate impact.",
      references: ["https://owasp.org/www-community/attacks/xss/"],
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(201),
      scan_id: uid(100),
      type: "SQL Injection",
      severity: "critical",
      cvss_score: 9.8,
      cvss_vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      cwe: "CWE-89",
      title: "SQL Injection in Login Endpoint",
      url: "https://juice-shop.herokuapp.com/rest/user/login",
      parameter: "email",
      method: "POST",
      evidence: "' OR 1=1-- returned 200 OK with valid session token",
      confirmed: true,
      fix_recommendation: "Use parameterized queries or prepared statements. Never concatenate user input into SQL queries directly.",
      references: ["https://owasp.org/www-community/attacks/SQL_Injection"],
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(202),
      scan_id: uid(100),
      type: "IDOR",
      severity: "high",
      cvss_score: 7.1,
      cvss_vector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:N",
      cwe: "CWE-639",
      title: "Insecure Direct Object Reference in User Profile API",
      url: "https://juice-shop.herokuapp.com/api/Users/",
      parameter: "id",
      method: "GET",
      evidence: "Changing user ID in URL exposes other users' PII (email, address, payment info)",
      confirmed: true,
      fix_recommendation: "Implement proper authorization checks. Verify the authenticated user has permission to access the requested resource.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(203),
      scan_id: uid(100),
      type: "Sensitive Data Exposure",
      severity: "medium",
      cvss_score: 5.3,
      cvss_vector: null,
      cwe: "CWE-200",
      title: "Directory Listing Enabled on /ftp",
      url: "https://juice-shop.herokuapp.com/ftp",
      parameter: null,
      method: "GET",
      evidence: "Directory listing reveals confidential files: acquisitions.md, coupons_2023.md, package.json.bak",
      confirmed: true,
      fix_recommendation: "Disable directory listing in the web server configuration. Remove sensitive files from publicly accessible directories.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(204),
      scan_id: uid(100),
      type: "Security Misconfiguration",
      severity: "medium",
      cvss_score: 4.3,
      cvss_vector: null,
      cwe: "CWE-16",
      title: "Missing Content-Security-Policy Header",
      url: "https://juice-shop.herokuapp.com/",
      parameter: null,
      method: "GET",
      evidence: "Response headers lack Content-Security-Policy, allowing inline scripts and external resource loading",
      confirmed: false,
      fix_recommendation: "Add a strict Content-Security-Policy header. Start with a report-only policy and gradually tighten restrictions.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(205),
      scan_id: uid(100),
      type: "Information Disclosure",
      severity: "low",
      cvss_score: 3.1,
      cvss_vector: null,
      cwe: "CWE-200",
      title: "Server Version Disclosed in Response Headers",
      url: "https://juice-shop.herokuapp.com/",
      parameter: null,
      method: "GET",
      evidence: "X-Powered-By: Express; Server header reveals technology stack",
      confirmed: true,
      fix_recommendation: "Remove or obfuscate server version headers. Disable X-Powered-By in Express configuration.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
    {
      id: uid(206),
      scan_id: uid(100),
      type: "Cookie",
      severity: "info",
      cvss_score: null,
      cvss_vector: null,
      cwe: "CWE-614",
      title: "Session Cookie Missing Secure Flag",
      url: "https://juice-shop.herokuapp.com/",
      parameter: null,
      method: "GET",
      evidence: "Set-Cookie: token=eyJ...; Path=/  (missing Secure and SameSite attributes)",
      confirmed: true,
      fix_recommendation: "Set Secure, HttpOnly, and SameSite=Strict flags on all session cookies.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(2),
    },
  ],
  [uid(101)]: [
    {
      id: uid(210),
      scan_id: uid(101),
      type: "XSS",
      severity: "high",
      cvss_score: 6.8,
      cvss_vector: null,
      cwe: "CWE-79",
      title: "Stored XSS in Feedback Form",
      url: "https://demo.testfire.net/feedback",
      parameter: "comment",
      method: "POST",
      evidence: "<img src=x onerror=alert(1)> stored and rendered for all users",
      confirmed: true,
      fix_recommendation: "Sanitize all user input before storage and apply output encoding when rendering.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(5),
    },
    {
      id: uid(211),
      scan_id: uid(101),
      type: "CSRF",
      severity: "medium",
      cvss_score: 5.4,
      cvss_vector: null,
      cwe: "CWE-352",
      title: "Missing CSRF Token on Money Transfer",
      url: "https://demo.testfire.net/bank/transfer",
      parameter: null,
      method: "POST",
      evidence: "Transfer endpoint accepts requests without anti-CSRF token validation",
      confirmed: true,
      fix_recommendation: "Implement CSRF tokens for all state-changing operations. Use SameSite cookie attribute as defense-in-depth.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(5),
    },
    {
      id: uid(212),
      scan_id: uid(101),
      type: "Information Disclosure",
      severity: "low",
      cvss_score: 2.6,
      cvss_vector: null,
      cwe: "CWE-200",
      title: "Verbose Error Messages Expose Stack Traces",
      url: "https://demo.testfire.net/api/error",
      parameter: null,
      method: "GET",
      evidence: "Java stack trace visible in 500 error response including class names and line numbers",
      confirmed: false,
      fix_recommendation: "Configure custom error pages. Disable detailed error output in production.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(5),
    },
  ],
  [uid(103)]: [
    {
      id: uid(220),
      scan_id: uid(103),
      type: "Broken Authentication",
      severity: "critical",
      cvss_score: 9.1,
      cvss_vector: null,
      cwe: "CWE-287",
      title: "JWT Secret Key Brute-Forceable (Weak Secret)",
      url: "https://example-bank.com/api/auth",
      parameter: null,
      method: "POST",
      evidence: "JWT signed with HS256 using weak secret 'secret123' - verified via jwt_tool",
      confirmed: true,
      fix_recommendation: "Use a cryptographically random secret of at least 256 bits. Consider switching to RS256 with key rotation.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(8),
    },
    {
      id: uid(221),
      scan_id: uid(103),
      type: "SSRF",
      severity: "high",
      cvss_score: 8.2,
      cvss_vector: null,
      cwe: "CWE-918",
      title: "Server-Side Request Forgery via PDF Export",
      url: "https://example-bank.com/api/statements/export",
      parameter: "template_url",
      method: "POST",
      evidence: "Setting template_url to http://169.254.169.254/latest/meta-data/ returned AWS metadata",
      confirmed: true,
      fix_recommendation: "Validate and whitelist allowed URLs. Block requests to private IP ranges and cloud metadata endpoints.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(8),
    },
    {
      id: uid(222),
      scan_id: uid(103),
      type: "Security Misconfiguration",
      severity: "medium",
      cvss_score: 5.0,
      cvss_vector: null,
      cwe: "CWE-16",
      title: "CORS Allows Arbitrary Origins",
      url: "https://example-bank.com/api/",
      parameter: null,
      method: "OPTIONS",
      evidence: "Access-Control-Allow-Origin reflects request Origin header including attacker-controlled domains",
      confirmed: true,
      fix_recommendation: "Restrict CORS to a whitelist of trusted origins. Avoid reflecting the Origin header directly.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(8),
    },
    {
      id: uid(223),
      scan_id: uid(103),
      type: "Information Disclosure",
      severity: "info",
      cvss_score: null,
      cvss_vector: null,
      cwe: "CWE-200",
      title: "robots.txt Reveals Admin Panel Path",
      url: "https://example-bank.com/robots.txt",
      parameter: null,
      method: "GET",
      evidence: "Disallow: /admin-portal/\nDisallow: /internal-api/",
      confirmed: true,
      fix_recommendation: "Protect admin endpoints with authentication rather than relying on obscurity. Remove sensitive paths from robots.txt.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(8),
    },
  ],
  [uid(105)]: [
    {
      id: uid(230),
      scan_id: uid(105),
      type: "Security Misconfiguration",
      severity: "low",
      cvss_score: 3.7,
      cvss_vector: null,
      cwe: "CWE-693",
      title: "Missing X-Frame-Options Header",
      url: "https://staging.myapp.io/",
      parameter: null,
      method: "GET",
      evidence: "No X-Frame-Options or frame-ancestors CSP directive set, potentially allowing clickjacking",
      confirmed: false,
      fix_recommendation: "Set X-Frame-Options: DENY or use Content-Security-Policy: frame-ancestors 'none'.",
      references: null,
      false_positive: false,
      notes: null,
      discovered_at: ago(1),
    },
  ],
};

// ── Finding Summaries ───────────────────────────────────────────────────
function buildSummary(findings: Finding[]): FindingSummary {
  const s: FindingSummary = { total: findings.length, critical: 0, high: 0, medium: 0, low: 0, info: 0, confirmed: 0, false_positives: 0 };
  for (const f of findings) {
    s[f.severity]++;
    if (f.confirmed) s.confirmed++;
    if (f.false_positive) s.false_positives++;
  }
  return s;
}

export const mockSummaries: Record<string, FindingSummary> = {};
for (const [scanId, findings] of Object.entries(mockFindings)) {
  mockSummaries[scanId] = buildSummary(findings);
}

// ── Reports ─────────────────────────────────────────────────────────────
export const mockReports: Record<string, Report> = {
  [uid(100)]: {
    id: uid(300),
    scan_id: uid(100),
    report_type: "technical",
    status: "ready",
    file_path: "/reports/report_100.pdf",
    share_token: "abc123def456",
    generated_at: ago(2),
    created_at: ago(2),
  },
  [uid(103)]: {
    id: uid(301),
    scan_id: uid(103),
    report_type: "executive",
    status: "ready",
    file_path: "/reports/report_103.pdf",
    share_token: null,
    generated_at: ago(7),
    created_at: ago(8),
  },
};

// ── Agent Logs ──────────────────────────────────────────────────────────
function makeLogs(scanId: string, agents: string[], baseMinutes: number): AgentLog[] {
  const levels = ["info", "info", "info", "info", "warning"];
  const messages: Record<string, string[]> = {
    recon: [
      "Starting reconnaissance on target",
      "DNS enumeration found 12 subdomains",
      "Port scan: 80, 443, 8080 open",
      "Technology fingerprint: Node.js, Express, Angular",
      "Collected 47 URLs from sitemap and crawl",
    ],
    scanner: [
      "Initializing vulnerability scanner",
      "Testing for XSS on 47 endpoints",
      "Testing for SQL injection on 23 parameters",
      "Testing for CSRF on 8 forms",
      "Found 3 potential vulnerabilities",
    ],
    exploit: [
      "Starting exploit verification",
      "Verifying XSS on /rest/products/search — CONFIRMED",
      "Verifying SQLi on /rest/user/login — CONFIRMED",
      "Verification complete: 2/3 confirmed",
    ],
    analyzer: [
      "Running AI-powered analysis",
      "Calculating CVSS scores for 7 findings",
      "Mapping CWE identifiers",
      "Generating fix recommendations",
      "Analysis complete — 1 critical, 2 high, 2 medium, 1 low, 1 info",
    ],
    reporter: [
      "Generating PDF report",
      "Building executive summary",
      "Adding detailed findings section",
      "Report generated successfully (24 pages)",
    ],
  };
  const logs: AgentLog[] = [];
  let minOffset = 0;
  for (const agent of agents) {
    const msgs = messages[agent] || ["Processing..."];
    for (let j = 0; j < msgs.length; j++) {
      logs.push({
        id: uid(400 + logs.length),
        scan_id: scanId,
        agent_name: agent,
        level: levels[j % levels.length],
        message: msgs[j],
        data: null,
        timestamp: agoMin(baseMinutes - minOffset),
      });
      minOffset += 1;
    }
  }
  return logs;
}

export const mockLogs: Record<string, AgentLog[]> = {
  [uid(100)]: makeLogs(uid(100), ["recon", "scanner", "exploit", "analyzer", "reporter"], 2 * 24 * 60),
  [uid(101)]: makeLogs(uid(101), ["recon", "scanner"], 5 * 24 * 60),
  [uid(102)]: makeLogs(uid(102), ["recon", "scanner"], 12),
  [uid(103)]: makeLogs(uid(103), ["recon", "scanner", "exploit", "analyzer", "reporter"], 8 * 24 * 60),
  [uid(105)]: makeLogs(uid(105), ["recon", "scanner"], 1 * 24 * 60),
};

// ── Settings ────────────────────────────────────────────────────────────
export const mockSettings: Settings = {
  llm_provider: "claude",
  has_api_key: true,
  email: "demo@bugbounty.com",
  username: "demo",
};
